### ISSUE TITLE
Rotation issue on tag 2.0.4

### ISSUE THREAD

**Issue by alex-muntean** [DALTCORE/lara-pdf-merger#11]
Hello,

I have experienced an issue on 2.0.4, where the page is a little bit rotated clockwise. 
In 2.0.3 this problem does not occur. From what i see, it may be from this change:

```
--- a/src/LynX39/LaraPdfMerger/tcpdf/tcpdi_parser.php
+++ b/src/LynX39/LaraPdfMerger/tcpdf/tcpdi_parser.php
@@ -1389,7 +1389,7 @@ class tcpdi_parser {
             if (!isset ($obj[1][1]['/Parent'])) {
                 return false;
             } else {
-                $res = $this->_getPageRotation($obj[1][1]['/Parent']);
+                $res = $this->getObjectVal($obj[1][1]['/Parent']);
```

Please let me know if you need any more information and thank you for the work on the package.

**Comment by RamonSmit** [comment]
Hi @alex-muntean, 

Thanks for your report! I'm going to look into this. Thanks for noticing it!

**Comment by RamonSmit** [comment]
@alex-muntean if you change this locally on your setup, the issue is gone?

**Comment by luisdalmolin** [comment]
@RamonSmit I'm having the same issue on 2.0.4, and it doesn't happen on 2.0.3.

**Comment by RamonSmit** [comment]
Thank for your comment! In that case i'm going to change that line.

**Comment by RamonSmit** [comment]
Can you please test against f896459 to see if this resolves it now?

Edit: also available on the 2.0.x-dev channel via Packagist

**Comment by yaroslavpopovic** [comment]
> Can you please test against [f896459](https://github.com/DALTCORE/lara-pdf-merger/commit/f896459451659b1ecbdfa20ac057aedcf6ef733a) to see if this resolves it now?
> 
> Edit: also available on the 2.0.x-dev channel via Packagist

I confirm, its solved

**Comment by luisdalmolin** [comment]
Thanks @RamonSmit!

**Comment by williamdes** [comment]
#12

**Comment by RamonSmit** [comment]
Thanks for the feedback guys!

**Comment by RamonSmit** [comment]
By the way, 

Tagged 2.0.5 on the rotation issue fix

**Comment by alex-muntean** [comment]
It seems ok now. Thanks and sorry for the late reply

**Comment by RamonSmit** [comment]
> It seems ok now. Thanks and sorry for the late reply

No problem, glad it works out! 👍

**Comment by williamdes** [comment]
@RamonSmit it looks like you did not import into GitHUb one of your GPG keys "8A98FF8CA461565D"

**Comment by RamonSmit** [comment]
> @RamonSmit it looks like you did not import into GitHUb one of your GPG keys "8A98FF8CA461565D"

But now it is 😄

**Comment by yagrasdemonde** [comment]
Hum for me I have a problem with 2.0.5, merge() crash !
With 2.0.4 merge() works but output PDF have a rotation, and with 2.0.5 I have this error :

**Trying to access array offset on value of type bool**

```json
"exception": "ErrorException",
    "file": "/Volumes/Data/WEB/www-local/lab/client/vendor/daltcore/lara-pdf-merger/src/LynX39/LaraPdfMerger/tcpdf/tcpdi_parser.php",
    "line": 1393,
```

```json
"message": "Trying to access array offset on value of type bool",
    "exception": "ErrorException",
    "file": "/Volumes/Data/WEB/www-local/lab/client/vendor/daltcore/lara-pdf-merger/src/LynX39/LaraPdfMerger/tcpdf/tcpdi_parser.php",
    "line": 1393,
    "trace": [
        {
            "file": "/Volumes/Data/WEB/www-local/lab/client/vendor/daltcore/lara-pdf-merger/src/LynX39/LaraPdfMerger/tcpdf/tcpdi_parser.php",
            "line": 1393,
            "function": "handleError",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/WEB/www-local/lab/client/vendor/daltcore/lara-pdf-merger/src/LynX39/LaraPdfMerger/tcpdf/tcpdi_parser.php",
            "line": 1378,
            "function": "_getPageRotation",
            "class": "tcpdi_parser",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/WEB/www-local/lab/client/vendor/daltcore/lara-pdf-merger/src/LynX39/LaraPdfMerger/tcpdf/tcpdi.php",
            "line": 204,
            "function": "getPageRotation",
            "class": "tcpdi_parser",
            "type": "->"
        },
```
Can you help me ?
Thank you
