### ISSUE TITLE
You made our PDF sink

### ISSUE THREAD

**Issue by williamdes** [DALTCORE/lara-pdf-merger#12]
`- Updating daltcore/lara-pdf-merger (2.0.3 => 2.0.4): Downloading (100%)`

### Before

![Sélection_2020040118:04:40001](https://user-images.githubusercontent.com/7784660/78160042-aea68180-7443-11ea-918d-4f105fe6c6a9.jpg)

### After

![Sélection_2020040118:06:32001](https://user-images.githubusercontent.com/7784660/78160062-b5cd8f80-7443-11ea-8776-54588be52d24.jpg)

cc @RamonSmit

**Comment by williamdes** [comment]
Fixed by https://github.com/DALTCORE/lara-pdf-merger/commit/f896459451659b1ecbdfa20ac057aedcf6ef733a

**Comment by RamonSmit** [comment]
Down like a ship ⛵️ ! 

Going to tag 2.0.5. Closing in favour of #11

**Comment by williamdes** [comment]
Thank you !
