### ISSUE TITLE
UnexpectedValueException - The Response content must be a string or object implementing __toString(), "boolean" given

### ISSUE THREAD

**Issue by alex-muntean** [DALTCORE/lara-pdf-merger#13]
Hello,

I receive an error which fills up the logs when people download PDFs. We open the PDF's with I options from inline and the return on this will be true.
Please see PdfManage.php - line 139

135-143
```php
if ($mode == 'S') {
    return $this->_fpdi->Output($outputpath, 'S');
} else {
    if ($this->_fpdi->Output($outputpath, $mode) == '') {
        return true; // error occurs from here
    } else {
        throw new Exception("Error outputting PDF to '$outputmode'.");
    }
}
```

**The full error:**

> The Response content must be a string or object implementing __toString(), "boolean" given. {"userId":1,"exception":"[object] (UnexpectedValueException(code: 0): The Response content must be a string or object implementing __toString(), \"boolean\" given. at /var/.../vendor/symfony/http-foundation/Response.php:406)

This is due to the fact that Laravel expects the response to be an string or object that implements __toString(), obviously boolean doesn't. I changed the line 
```php
return true;
```
with 
```php
return ['message' => true];
```
and the problem doesn't occur anymore.

Can you take a look on this one please?
I am using version 2.0.5 and Laravel version 5.8.37.

Thanks,
Alex

**Comment by RamonSmit** [comment]
I think its the best if you lock at tag `2.0.3` or stream it correctly to the response. The PDF generator is not build to invoke with the Symfony response 

```php
return Response::make($pdf, 200, [
    'Content-Type' => 'application/pdf',
    'Content-Disposition' => 'inline; filename='pdf.pdf'
]);
```
