### ISSUE TITLE
Issue with Illumine

### ISSUE THREAD

**Issue by JesusLopezMadrid** [DALTCORE/lara-pdf-merger#4]
Hi, I have a problem with the code. I have inserted the Illumine / support code but it gives me an error in the $ pdfMerger = PDFMerger :: init ();
Fatal error: Uncaught RuntimeException: A facade root has not been set. in /var/www/html/es/lib/vendorIlluminate/illuminate/support/Facades/Facade.php:236 Stack trace: # 0 /var/www/html/es/validate_test.php(280): Illuminate \ Support \ Facades \ Facade :: __ callStatic ('init', Array) # 1 {main} thrown in /var/www/html/es/lib/vendorIlluminate/illuminate/support/Facades/Facade.php on line 236

**Comment by RamonSmit** [comment]
I'm wondering how your vendor directory got like "vendorIlluminate" ? Might be there?

What is your Laravel version and what is your PHP version?

**Comment by JesusLopezMadrid** [comment]
I do not use Laravel, is it required? I have version 7.2 of php

**Comment by RamonSmit** [comment]
Yes, This package is specially written for use with the Laravel Framework
