### ISSUE TITLE
No Constructor

### ISSUE THREAD

**Issue by jsandfordhughes** [DALTCORE/lara-pdf-merger#8]
I couldn't get the merge to work at all, had a call to member function setSourceFile on null.

Checked the code and the init function was not being called so the _fpdi function was not instantiated. 

I added a constructor with the init function at the top of the PdfManage.php file and now all working fine?

**Comment by RamonSmit** [comment]
How do you mean? Do you have a code example? :)

**Comment by jsandfordhughes** [comment]
This is the init function


 ```
public function init(){
         $this->_files = null;

         $this->_fpdi = new TCPDI;
         $this->_fpdi->setPrintHeader(false);
         $this->_fpdi->setPrintFooter(false);

         return $this;
 }
```

It is not instantiated and because of this the var _fdpi is null when this function gets called

`$count = $this->_fpdi->setSourceFile($filename);`

I have added the init function into a constructor and now it works fine

```
function __construct()
    {
        $this->init();

    }

    public function init(){
        $this->_files = null;

        $this->_fpdi = new TCPDI;
        $this->_fpdi->setPrintHeader(false);
        $this->_fpdi->setPrintFooter(false);

        return $this;
    }
```

**Comment by RamonSmit** [comment]
On what version are you? I can't imagine that this wouldn't work on Laravel?
