### ISSUE TITLE
PHP 7.4 - Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by nchatzidakis** [DALTCORE/lara-pdf-merger#9]
In PHP 7.4.1 I get an error in `PDFMerger::init();`
ErrorException: Array and string offset access syntax with curly braces is deprecated in /home/vagrant/code/MYPROJECT/vendor/daltcore/lara-pdf-merger/src/LynX39/LaraPdfMerger/tcpdf/tcpdf.php:16893

In PHP 7.3 and older versions worked fine.

By replacing curly braces problem seems solve this problem, but it more php errors occurs after.

**Comment by RamonSmit** [comment]
We know, in #5 we're trying to solve it!
